version: "3.8"

x-service-volumes: &service-volumes
  - ./hiyield:/hiyield/:rw,cached
  - ./data/web:/vol/web

x-database-variables: &database-variables
  POSTGRES_USER: djangouser
  POSTGRES_PASSWORD: djangopostgres
  POSTGRES_DB: voting
  POSTGRES_HOST: postgres

# used variable so its easy to setup to test
# I wouldn't do this in production

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: postgres
  DEBUG: 1
  SECRET_KEY: "supersupersecret"
  ALLOWED_HOSTS: 0.0.0.0

services:
  web:
    image: django-postgres
    build:
      context: .
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate  &&           
        python manage.py runserver 0.0.0.0:8088"
    ports:
      - 8088:8088
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment: *database-variables
    ports:
      - "5432"

volumes:
  db-data:
